language: scala
sudo: required
jdk:
  - oraclejdk8
env:
  global:
    - TRAVIS_NODE_VERSION="8"
matrix:
  include:
  - env: TRAVIS_SBT_VERSION="0.13.16"
  - env: TRAVIS_SBT_VERSION="1.0.2"
before_install:
  # Install Node.js and yarn.
  - nvm install 6
  - nvm use 6
  - node --version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.24.6
  - export PATH=$HOME/.yarn/bin:$PATH
script:
  - sbt -no-colors ";^^$TRAVIS_SBT_VERSION;test;runScripted"
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
